# Site settings
title: "Carlos Requena"
description: "Carlos Requena. Software Engineer, coding, maths, distributed systems, performance optimisation, cloud computing, Amazon Web Services, AWS, blockchain."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Carlos José Requena Jiménez"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "cjrequena@outlook.es"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Software Engineer and IT Solution Architect result-oriented and focused on delivering results. Skilled in cloud computing, distributed systems, software architecture, microservices, event-driven architecture, design patterns, software development, TDD, DevOps. Demonstrated mastery in evaluating requirements for business application integration and service activation. Proven mentoring and training with expertise in communicating across organizational levels and with cross-functional teams to drive the shared vision and foster a culture of excellence.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_courses:         true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/cjrequena/"
  resume_twitter_url:           "http://twitter.com/cjrequena"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/cjrequena/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://cjrequena.com"
  resume_medium_url:            "https://medium.com/@cjrequena"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
